version: "3"

services:
  front:
    build: ./front-sk
    image: front:0.1
    ports: - 8080:8080

  back:
    build: ./back-sk
    image: back:0.1
    ports: - 8000:8080
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    ports: - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ssafyssafyroomroom
      MYSQL_DATABASE: ssafy
      MYSQL_USER: root


